server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service_v_2"
    username: root
    password: qweasdzxc
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
